### ISSUE TITLE
Ef core 2.0 compatible ??

### ISSUE THREAD

**Issue by Diaskhan** [ovation22/GenericRepositoryDIwithNETCore#1]
Hie Comrad!
I have a question.

This solution is Ef core 2.0 compatible ??

**Comment by ovation22** [comment]
Yes, it is @Diaskhan. You might have to update some NuGet packages, but it should all work.

**Comment by Diaskhan** [comment]
Maybe U could help !
How to make solution with pluginable assemly ?
Something similar to https://stackoverflow.com/questions/8730830/mef-plugins-and-ef-codefirst-how

I want to make model design from GUI and then aplly model to working Web application !

It's sad that net core doesnt provide unloading assemlies !
